name: Build Mod

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extract source
        run: |
          mkdir source
          unzip -q ./*source.zip -d source

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Find project
        run: |
          PROJECT=$(find source -type f -name build.gradle | head -n 1 | xargs dirname)
          echo "PROJECT=$PROJECT" >> "$GITHUB_ENV"

      - name: Build with Gradle
        run: |
          cd "$PROJECT"
          gradle --refresh-dependencies build --no-daemon

      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: S7rawi-Elemental-Pickaxe-JAR
          path: "**/build/libs/*.jar"
